apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: circleci-container-runner
spec:
  collectors:
    - logs:
        selector:
          - app=container-agent
        name: container-agent
        limits:
          # last 3 days
          maxAge: 72h
          maxLines: 1000
    - logs:
        selector:
          - app.kubernetes.io/name=circleci-task-agent
          - app.kubernetes.io/managed-by=circleci-container-agent
        name: container-task
    - http:
        collectorName: runnerAPI
        get:
          url: https://runner.circleci.com/api/v2/runner?namespace=foobar
          insecureSkipVerify: true
          headers:
            Circle-Token: "dummy"
  analyzers: []
